modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/OreTexGen/"

[[mods]]
	modId="oretexgen"
	version="${mod_version}"
	displayName="OreTexGen"
	#displayURL="https://www.curseforge.com/minecraft/mc-mods/oretexgen"
	logoFile="logo.png"
	authors="Love, Cheese and small house plants"
	displayTest="IGNORE_ALL_VERSION"
	description='''
	'''

[[dependencies.oretexgen]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.oretexgen]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.oretexgen]]
    modId="atlasviewer"
    mandatory=false
    versionRange="[5.1.1,)"
    ordering="NONE"
    side="BOTH"
